name: Github Action Test
run-name: ${{ github.actor }} - ${{ vars.OPEN }} - started Deploy with gh-pages ðŸš€
on:
  push:
    branches:
      - feat/test-build-main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: TESTE ENV
        env:
          OPEN: ${{ vars.OPEN }}
          REACT_APP_FIREBASE_TYPE: ${{ secrets.REACT_APP_FIREBASE_TYPE }}
        run: |
          echo "TESTE ENV - secrets.REACT_APP_FIREBASE_TYPE"
          echo "$REACT_APP_FIREBASE_TYPE"
          echo ${{ github.repository }}
          echo "$OPEN"
        